OSX localzone should not require sudo
Rather than using `sudo systemsetup -gettimezone` once can get the localzone on OSX based on `/etc/localtime` (i.e., no sudo required). Should fix issue with 
```
ERROR: IOError: could not spawn `systemsetup -gettimezone`: no such file or directory (ENOENT)
```
on various applications such as VS Code even with full disk privileges.