Fix Windows when treating FixedTimeZone as path
Since `TimeZone` can now deals with parsing FixedTimeZone strings there
are scenarios where we could accidentally try to use the string as a
path where it can break things. For example if a fixed time zone
contains a colon we can get the following which was found by our tests:

```
Test threw an exception of type ArgumentError
Expression: ZonedDateTime("1942-12-25T01:23:45.000+01:00") == ZonedDateTime(dt, fixed)
ArgumentError: drive mismatch: C:\Users\appveyor\.julia\v0.6\TimeZones\deps\compiled +01:00
```