Embed Windows to POSIX translation file
It appears that Appveyor is no longer allowed to download the
windowsZones.xml file from unicode.org:

```
LoadError: automatic download failed (error: 2148270085): http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml
```

In order to address this I have committed a copy of the 2017a
windowsZones.xml file to fallback on in case downloading this file fails
under Windows.